### ISSUE TITLE
Can't get item 2

### ISSUE THREAD

**Issue by Kent-Narun** [Soorma07/OS-X-Bluetooth-Pairing-Value-To-Windows-Value#1]
<img width="1440" alt="screen shot 2018-08-02 at 10 02 17 am" src="https://user-images.githubusercontent.com/41314683/43560110-389843c6-963b-11e8-91b9-3e31a4487c83.png">
I can't execute the script please help!!!

**Comment by Soorma07** [comment]
Interesting. Is there some issue with your pairing keys? It help looking at what the command below lists out for you.

sudo defaults read /private/var/root/Library/Preferences/blued.plist

**Comment by liquuid** [comment]
> sudo defaults read /private/var/root/Library/Preferences/blued.plist

On High Sierra this is not a valid path, the new one is: 

```
sudo defaults read /private/var/root/Library/Preferences/com.apple.bluetoothd.plist
{
    LinkKeys =     {
        "b8-f6-b1-38-89-a1" =         {
            "30-21-7d-5d-4d-63" = <84386cd5 b8c80ffe 4d49db35 f7fbec4e>;
            "b8-f6-b1-27-19-51" = <b87ef4a9 119b6e07 84c6a669 0ffba32a>;
            "c8-e0-eb-07-da-53" = <0d588642 b16bcbc3 2cbf619f 2bfdb4fa>;
        };
    };
    MagicCloudPairingMasterHint = <7e5b6e4a 2b5c529b b6fac11d 7fa4f07c>;
    MagicCloudPairingMasterKey = <8b799034 78d79b6c d0c598cf 52d305c3>;
}
```

**Comment by Soorma07** [comment]
Integrated the new namespace
