### ISSUE TITLE
Can't get item 2 macOS Mojave

### ISSUE THREAD

**Issue by echthesia** [Soorma07/OS-X-Bluetooth-Pairing-Value-To-Windows-Value#2]
The "Can't get item 2" bug from issue #1 has made a return in macOS Mojave. The symptoms are the exact same as in the previous issue. They persist even after changing the permissions of the relevant folders, which are by default set to only allow the system account access.

**Comment by Soorma07** [comment]
I'll upgrade to macOS Mojave and try it out. Any suggestions for a fix?

**Comment by Soorma07** [comment]
Did you try both of these terminal commands? They both work for me in macOS Mojave.

`sudo defaults read /private/var/root/Library/Preferences/blued.plist
`
`sudo defaults read /private/var/root/Library/Preferences/com.apple.bluetoothd.plist
`

**Comment by Soorma07** [comment]
Maybe it's case sensitive. I'll merge this 

`sudo defaults read /private/var/root/Library/Preferences/com.apple.Bluetooth.plist`

**Comment by Soorma07** [comment]
I merged some changes to now first try `blued.plist` then if that fails to try `com.apple.bluetoothd.plist`. I hope this resolves your issue! Otherwise, please run the commands in terminal and provide a possible solution.
