### ISSUE TITLE
Catalina Support

### ISSUE THREAD

**Issue by lignicolos** [Soorma07/OS-X-Bluetooth-Pairing-Value-To-Windows-Value#3]
I can't seem to get this to work in Catalina.  I get the message below.

![Screen Shot 2019-10-27 at 6 40 53 PM](https://user-images.githubusercontent.com/27593909/67643074-52b25c80-f8e9-11e9-9b62-78a55d052618.png)

**Comment by arvenil** [comment]
No idea which value I should choose as key. I guess maybe before Catalina this data structure looked differently?
```
sudo defaults read /private/var/root/Library/Preferences/com.apple.bluetoothd.plist
{
    LinkKeys =     {
        "38-f9-d3-45-ec-8f" =         {
            "28-11-a5-db-0d-b1" = {length = 16, bytes = 0xbde83de1c4067ee0e6a9ef89caf9f075};
            "cc-98-8b-a7-a0-19" = {length = 16, bytes = 0x3e03f0f74a1570994bd7e1be255cc87f};
            "f4-bf-80-0d-84-7f" = {length = 16, bytes = 0x5079503a79cd5d3e6ebc1c9805373f78};
        };
        "38-f9-d3-d5-a7-df" =         {
            "4c-87-5d-2b-de-5f" = {length = 16, bytes = 0x8776b2212ec8096efb82f429ef59b32b};
            "f4-bf-80-0d-84-7f" = {length = 16, bytes = 0xb53a09375cbe4c33601a4e42c8dcf938};
        };
    };
    SMPCloudLocalNonce = {length = 16, bytes = 0xe9ada2ae5c15cd4b4c645c23818f0857};
    SMPCloudLocalPrivateKey = {length = 96, bytes = 0x8f99b9a7 b501199a 9d6881b2 9d0139b8 ... 24210413 fde1b098 };
    SMPCloudLocalPublicKey = {length = 64, bytes = 0x8f99b9a7 b501199a 9d6881b2 9d0139b8 ... 623d8a0a 81d79463 };
}
```

**Comment by Soorma07** [comment]
Yeah, it looks like Apple is now encrypting the Bluetooth key/value pairs. I’m not sure how to decrypt the bytes to get the real values anymore.

**Comment by Broeckelmaier** [comment]
I've come across this tool on my quest to dual-pair my headset.
As it turns out the keys are still in the output.
you just have to cut the
> length = 16, bytes = 0x

and end up with the pairing key as before.
In your case @arvenil the key for your Sony headset would be
> 3e03f0f74a1570994bd7e1be255cc87f

You'll just have to give it the same treatment to make it windows compatible.
So you end up with
> 7f c8 5c 25 be e1 d7 4b 99 70 15 4a f7 f0 03 3e

or if you want to have it in a .reg file it would look like this:

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\BTHPORT\Parameters\Keys]

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\BTHPORT\Parameters\Keys\38f9d345ec8f]
"cc988ba7a019"=hex:7f,c8,5c,25,be,e1,d7,4b,99,70,15,4a,f7,f0,03,3e

```

**Comment by Broeckelmaier** [comment]
@Soorma07 before parsing you could check which osx version is installed and parse the data accordingly

```
set _versionString to system version of (system info)

considering numeric strings
	if _versionString ≤ "10.12" then
		-- read /private/var/root/Library/Preferences/blued.plist
	else if (_versionString > "10.12") and (_versionString < "10.15") then
		-- read /private/var/root/Library/Preferences/com.apple.Bluetoothd.plist
	else if _versionString ≥ "10.15" then
		-- read /private/var/root/Library/Preferences/com.apple.Bluetoothd.plist but parse it differently
	else
		set _errorText to "Congratulations, you've found the edge case"
		display dialog _errorText with icon stop
	end if
end considering
```

**Comment by wentaoStudy** [comment]
> @Soorma07 before parsing you could check which osx version is installed and parse the data accordingly
> 
> ```
> set _versionString to system version of (system info)
> 
> considering numeric strings
> 	if _versionString ≤ "10.12" then
> 		-- read /private/var/root/Library/Preferences/blued.plist
> 	else if (_versionString > "10.12") and (_versionString < "10.15") then
> 		-- read /private/var/root/Library/Preferences/com.apple.Bluetoothd.plist
> 	else if _versionString ≥ "10.15" then
> 		-- read /private/var/root/Library/Preferences/com.apple.Bluetoothd.plist but parse it differently
> 	else
> 		set _errorText to "Congratulations, you've found the edge case"
> 		display dialog _errorText with icon stop
> 	end if
> end considering
> ```

    LinkKeys =     {
        "30-52-cb-80-78-92" =         {
        };
    };
    MagicCloudPairingMasterHint = {length = 16, bytes = 0x8fb9ac55aa2a64c39100ce4c223e2934};
    MagicCloudPairingMasterKey = {length = 16, bytes = 0xee05164be5e6aef8f5624ff03406c717};
    SMPCloudLocalNonce = {length = 16, bytes = 0x67e39008697d6268f589522b0c2c9833};
    SMPCloudLocalPrivateKey = {length = 96, bytes = 0x8e1efdad e49d42d6 60c7078f 679837d1 ... 8aa22645 3678be38 };
    SMPCloudLocalPublicKey = {length = 64, bytes = 0x8e1efdad e49d42d6 60c7078f 679837d1 ... a979a54a f86f0a7f };
    SMPDistributionKeys =     {
        "30-52-cb-80-78-92" =         {
            "ed-d6-74-4c-6b-7e" =             {
                Address = {length = 6, bytes = 0xedd6744c6b7e};
                AddressType = 1;
                EDIV = {length = 2, bytes = 0x14ce};
                IRK = {length = 16, bytes = 0x8952e32177618fba4fcc8c2de8e71cd8};
                LTK = {length = 16, bytes = 0xe9cafb38aaca959555e23ff0a5e93997};
                LTKLength = {length = 1, bytes = 0x10};
                MITMProtection = 0;
                OriginalAddressType = 1;
                RAND = {length = 8, bytes = 0x2b810fed88730e8c};
            };
        };
    };

这种带公钥和私钥的怎么搞

**Comment by wentaoStudy** [comment]
> @Broeckelmaier

how to deal this

 LinkKeys =     {
        "30-52-cb-80-78-92" =         {
        };
    };
    MagicCloudPairingMasterHint = {length = 16, bytes = 0x8fb9ac55aa2a64c39100ce4c223e2934};
    MagicCloudPairingMasterKey = {length = 16, bytes = 0xee05164be5e6aef8f5624ff03406c717};
    SMPCloudLocalNonce = {length = 16, bytes = 0x67e39008697d6268f589522b0c2c9833};
    SMPCloudLocalPrivateKey = {length = 96, bytes = 0x8e1efdad e49d42d6 60c7078f 679837d1 ... 8aa22645 3678be38 };
    SMPCloudLocalPublicKey = {length = 64, bytes = 0x8e1efdad e49d42d6 60c7078f 679837d1 ... a979a54a f86f0a7f };
    SMPDistributionKeys =     {
        "30-52-cb-80-78-92" =         {
            "ed-d6-74-4c-6b-7e" =             {
                Address = {length = 6, bytes = 0xedd6744c6b7e};
                AddressType = 1;
                EDIV = {length = 2, bytes = 0x14ce};
                IRK = {length = 16, bytes = 0x8952e32177618fba4fcc8c2de8e71cd8};
                LTK = {length = 16, bytes = 0xe9cafb38aaca959555e23ff0a5e93997};
                LTKLength = {length = 1, bytes = 0x10};
                MITMProtection = 0;
                OriginalAddressType = 1;
                RAND = {length = 8, bytes = 0x2b810fed88730e8c};
            };
        };
    };

**Comment by Broeckelmaier** [comment]
@wentaoStudy looks like your system has no bluetooth devices paired.
The linkkeys for every device/module reside between
`    LinkKeys =     {`
and
`    MagicCloudPairingMasterHint = {`

**Comment by wentaoStudy** [comment]
@Broeckelmaier  No i had paired a bluetooth mouse

**Comment by Broeckelmaier** [comment]
@wentaoStudy this seems more like a techsupport issue, and we shouldn't discuss it here.
You can dm me at broeckelmaier@web.de

**Comment by Soorma07** [comment]
Thanks @Broeckelmaier for the update! I've merged your pull request.
